apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "nfs_server_ip" #replace with acutal server ip
    path: /tmp/data/pv-1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-1
