apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: web

spec:

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3

  replicas: 5

  template:

    metadata:
      name: web
      labels:
        name: web
        app: demo

    spec:

      containers:
      - name: web
        image: k8s101web
        imagePullPolicy: IfNotPresent
        env:
          - name: "REDIS_HOST"
            value: "redis_pod_ip" #replace with acutal redis ip
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pv-1
          mountPath: /home/redis

      volumes:
      - name: pv-1
        persistentVolumeClaim: 
          claimName: pvc-1
