apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-client
        role: client
    spec:
      containers:
      - name: tf-client
        image: tensorflow/tensorflow:1.0.1
        ports:
        - containerPort: 8888
        env:
        - name: TOKEN
          value: "p@ssw0rd"
        command: ["/bin/sh", "-c"]
        args: ["
            rm -r /notebooks/*;
            curl https://gist.githubusercontent.com/kairen/0d983f72665227ccebaaf44fc83e9210/raw/f532f312fb5afa6c5f24d475b12e2faaf373d556/client.ipynb -o /notebooks/client.ipynb;
            /run_jupyter.sh --NotebookApp.token=${TOKEN};"]
        volumeMounts:
        - name: tmp
          mountPath: /tmp/train
      volumes:
        - name: tmp
          persistentVolumeClaim:
            claimName: lab01-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tf-client
spec:
  selector:
    app: tf-client
  type: LoadBalancer
  externalIPs:
  - 172.16.35.9
  ports:
  - port: 8888
    targetPort: 8888
