apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab01-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/lab01
    server: 172.16.35.12

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab01-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
